### ISSUE TITLE
Add a logo

### ISSUE THREAD

**Issue by no-reply** [UCLALibrary/samvera-mgmt#14]
The DCE logo is currently in the top nav bar, replace this with something appropriate for UCLA:

## Acceptance

  - [x] choose a (temporary?) logo
  - [ ] selected logo appears in the banner

**Comment by billha** [comment]
Confirmed this with @emcaulay. We will use the existing "UCLA Library" logo from the library web site: http://www.library.ucla.edu. Attached is the standard logo jpg file. The bar behind the UCLA logo should match the blue in the logo. The word "Library" is written to the right in white in Times New Roman with a font size similar to the size of the UCLA letters. 
![ucla-box-blu-rgb-1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b3fa159acf9c70015453b0d/125516c66e82c728ace21e0d46fd979622cf81a697a4bd4fb110e2932b0b76316546b3397f8fe62bab0021435a0d4df915595b4cf5a88922f7e33c708b0e0de4d66b5e71d42103eee9dc4be05ce36ade0d97bcae8b45cae93826e6828b483818041c89fe4f78.jpg)

**Comment by hardyoyo** [comment]
copying over from a Slack thread, quoting @no-reply : https://github.com/UCLALibrary/samvera-mgmt/commit/649ee9a1b4512d960623ca1c0049e5c0ff95540b and https://github.com/UCLALibrary/samvera-mgmt/commit/cc64a421c6c0ba647ffd5cc289f33332bc2f47f8 might be helpful breadcrumbs

**Comment by hardyoyo** [comment]
PR #20 addresses both #13 and #14

**Comment by hardyoyo** [comment]
the banner image is from this: http://oral-history-balancer-1368671073.us-west-2.elb.amazonaws.com/assets/ucla_hero_1920x400-654981fef0cfb41b18fa9f57a136881095ae66f1ab69b6c0499cbdf7bfbc5144.jpg I cropped it slightly (sorry, moon) so more of the skyline would be visible in the banner.
